name: agromotion
description: "App de controlo para sistema de alimentação automatizado AgroMotion."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  package_info_plus: ^9.0.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.0
  firebase_database: ^12.1.1
  firebase_messaging: ^16.1.0
  http: ^1.6.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/service-account.json
