name: agromotion
description: "App de controlo para sistema de alimentação automatizado AgroMotion."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  package_info_plus: ^9.0.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.0
  firebase_database: ^12.1.1
  firebase_messaging: ^16.1.0
  http: ^1.6.0
  googleapis_auth: ^2.0.0
  logger: ^2.6.2
  lottie: ^3.3.2
  flutter_cache_manager: ^3.4.1
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  google_sign_in_all_platforms: ^2.0.2
  flutter_dotenv: ^6.0.0
  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_512_launcher.png"
  
  adaptive_icon_background: "#FFFFFF" # Cor de fundo
  adaptive_icon_foreground: "assets/logo_512_launcher.png" 

  web:
    generate: true
    image_path: "assets/logo_w_512.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

  windows:
    generate: true
    image_path: "assets/logo_w_512.png"
    icon_size: 256

flutter:
  uses-material-design: true
  assets:
    - assets/service-account.json
    - assets/logo_512.png
    - assets/logo_512_launcher.png
    - assets/loading_indicator.json

  fonts:
    - family: AudibleSans
      fonts:
        # Regular
        - asset: assets/fonts/AudibleSans-Rg.ttf
        # Italic
        - asset: assets/fonts/AudibleSans-Italic.ttf
          style: italic
        # Light
        - asset: assets/fonts/AudibleSans-Lt.ttf
          weight: 300
        - asset: assets/fonts/AudibleSans-LightItalic.ttf
          weight: 300
          style: italic
        # Medium
        - asset: assets/fonts/AudibleSans-Md.ttf
          weight: 500
        # Bold (Bd)
        - asset: assets/fonts/AudibleSans-Bd.ttf
          weight: 700
        # Bold Italic
        - asset: assets/fonts/AudibleSans-BoldItalic.ttf
          weight: 700
          style: italic
        # SemiBold (Sm)
        - asset: assets/fonts/AudibleSans-Sm.ttf
          weight: 600
        - asset: assets/fonts/AudibleSans-SemiboldItalic.ttf
          weight: 600
          style: italic

